name: Autogenerate site
on:
  pull_request:
    branches: 
    - master
    - main
jobs:
  autogenerate-site:
    runs-on: ubuntu-latest
    name: Creating site for deployment

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: rodrigo-md/pull-request-visualizer-action@testing-action
